NOMS_FR = {
    "Abu Dhabi": "Abou Dabi", "Afghanistan": "Afghanistan", "Albania": "Albanie", "Algeria": "Algérie", "Angola": "Angola",
    "Antigua and Barbuda [1981-]": "Antigua-et-Barbuda", "Argentina": "Argentine", "Armenia": "Arménie",
    "Australia": "Australie", "Austria": "Autriche", "Azerbaijan": "Azerbaïdjan", "Bahamas": "Bahamas",
    "Bahamas [1973-]": "Bahamas (1973-)", "Bahrain": "Bahreïn", "Bangladesh": "Bangladesh", "Barbados [1966-]": "Barbade",
    "Belarus [1992-]": "Biélorussie", "Belgium": "Belgique", "Benin [1961-]": "Bénin", "Bolivia": "Bolivie",
    "Bosnia and Herzegovina [1992-]": "Bosnie-Herzégovine", "Botswana": "Botswana", "Brazil": "Brésil", "Brunei": "Brunei",
    "Bulgaria": "Bulgarie", "Burkina Faso [1960-]": "Burkina Faso", "Burundi [1962-]": "Burundi", "Cambodia": "Cambodge",
    "Cameroon": "Cameroun", "Canada": "Canada", "Central African Republic [1960-]": "Centrafrique", "Chad [1960-]": "Tchad",
    "Chechnya [1991-2000]": "Tchétchénie (1991-2000)", "Chile": "Chili", "China": "Chine", "Civilian": "Civil",
    "Colombia": "Colombie", "Commercial": "Commercial", "Congo [1960-]": "Congo", "Costa Rica": "Costa Rica",
    "Cote D'Ivoire [1960-]": "Côte d'Ivoire", "Croatia [1992-]": "Croatie", "Cuba": "Cuba", "Cyprus": "Chypre",
    "Czech Republic [1993-]": "Tchéquie", "Czechoslovakia  [-1992]": "Tchécoslovaquie (-1992)", "DRC/Zaire [1960-]": "RD Congo",
    "Denmark": "Danemark", "Djibouti [1977-]": "Djibouti", "Dominican Republic": "République dominicaine",
    "Ecuador": "Équateur", "Egypt": "Égypte", "El Salvador": "Salvador", "Equatorial Guinea": "Guinée équatoriale",
    "Eritrea [1993-]": "Érythrée", "Estonia [1992-]": "Estonie", "Ethiopia": "Éthiopie", "European Union [1993-]": "Union européenne",
    "Federated States of Micronesia": "Micronésie", "Fiji": "Fidji", "Finland": "Finlande", "France": "France", "Gabon": "Gabon",
    "Gambia [1965-]": "Gambie", "Generic": "Générique", "Georgia [1991-]": "Géorgie", "Germany [DDR, -1990]": "RDA (-1990)",
    "Germany [FRG/Reunified]": "Allemagne", "Germany [Nazi]": "Allemagne nazie", "Ghana": "Ghana", "Greece": "Grèce",
    "Guatemala": "Guatemala", "Guinea [1958-]": "Guinée", "Guyana [1966-]": "Guyana", "Hamas": "Hamas", "Honduras": "Honduras",
    "Hong Kong": "Hong Kong", "Hungary": "Hongrie", "Iceland": "Islande", "India": "Inde", "Indonesia": "Indonésie",
    "Iran": "Iran", "Iraq": "Irak", "Ireland": "Irlande", "Israel": "Israël", "Italy": "Italie", "Jamaica [1962-]": "Jamaïque",
    "Japan": "Japon", "Jordan": "Jordanie", "Junkyard": "Casse", "Kazakhstan [1992-]": "Kazakhstan", "Kenya": "Kenya",
    "Kuwait": "Koweït", "Kyrgyzstan": "Kirghizistan", "Laos": "Laos", "Latvia [1992-]": "Lettonie", "Lebanon": "Liban",
    "Lesotho": "Lesotho", "Libya": "Libye", "Lithuania [1992-]": "Lituanie", "Luxembourg": "Luxembourg",
    "Malawi [1966-]": "Malawi", "Malaysia": "Malaisie", "Maldives [1965-]": "Maldives", "Mali [1960-]": "Mali", "Malta": "Malte",
    "Mauritania [1960-]": "Mauritanie", "Mexico": "Mexique", "Moldova [1992-]": "Moldavie", "Mongolia": "Mongolie",
    "Montenegro [1992-]": "Monténégro", "Morocco": "Maroc", "Mozambique": "Mozambique", "Myanmar": "Birmanie",
    "NATO": "OTAN (moyens communs)", "Namibia": "Namibie", "Nepal": "Népal", "Netherlands": "Pays-Bas",
    "New Zealand": "Nouvelle-Zélande", "Nicaragua": "Nicaragua", "Niger": "Niger", "Nigeria": "Nigeria", "None": "Aucun",
    "North Korea": "Corée du Nord", "North Macedonia [1991-]": "Macédoine du Nord", "North Vietnam [-1975]": "Nord-Vietnam (-1975)",
    "Norway": "Norvège", "Oman": "Oman", "Pakistan": "Pakistan", "Panama": "Panama", "Papua New Guinea": "Papouasie-Nouvelle-Guinée",
    "Paraguay": "Paraguay", "Peru": "Pérou", "Philippines": "Philippines", "Pirates": "Pirates", "Poland": "Pologne",
    "Portugal": "Portugal", "Qatar": "Qatar", "Rebels": "Rebelles", "Rhodesia": "Rhodésie", "Romania": "Roumanie",
    "Russia [1992-]": "Russie", "Rwanda [1962-]": "Rwanda", "Saudi Arabia": "Arabie saoudite", "Senegal": "Sénégal",
    "Serbia [1992-]": "Serbie", "Singapore": "Singapour", "Slovakia [1993-]": "Slovaquie", "Slovenia [1991-]": "Slovénie",
    "Solomon Islands": "Îles Salomon", "Somalia": "Somalie", "South Africa": "Afrique du Sud", "South Korea": "Corée du Sud",
    "South Sudan": "Soudan du Sud", "South Vietnam [-1975]": "Sud-Vietnam (-1975)", "Soviet Union [-1991]": "URSS (-1991)",
    "Spain": "Espagne", "Sri Lanka": "Sri Lanka", "Sudan": "Soudan", "Suriname [1954-]": "Suriname", "Swaziland": "Eswatini",
    "Sweden": "Suède", "Switzerland": "Suisse", "Syria": "Syrie", "Taiwan": "Taïwan", "Tajikistan": "Tadjikistan",
    "Tanzania": "Tanzanie", "Terrorists": "Terroristes", "Thailand": "Thaïlande", "Timor Leste [1975-]": "Timor oriental",
    "Togo": "Togo", "Tonga": "Tonga", "Trinidad and Tobago [1962-]": "Trinité-et-Tobago", "Tunisia": "Tunisie",
    "Turkey": "Turquie", "Turkmenistan": "Turkménistan", "UAE": "Émirats arabes unis", "Uganda": "Ouganda",
    "Ukraine [1992-]": "Ukraine", "United Kingdom": "Royaume-Uni", "United States": "États-Unis", "Unknown": "Inconnu",
    "Uruguay": "Uruguay", "Uzbekistan": "Ouzbékistan", "Venezuela": "Venezuela", "Vietnam [1975-]": "Viêt Nam",
    "Yemen [1990-]": "Yémen", "Yugoslavia [-1992]": "Yougoslavie (-1992)", "Zambia": "Zambie", "Zimbabwe": "Zimbabwe",
}
