"""HMT-126 ( e ) : l ordre des depenses du menage pauvre ( domaines 3, 4, 6, 11, 12 ). Factures d electricite et
   d eau, taxe locale, cotisations des independants se paient au-dela de la semaine de nourriture ( domaine 3,
   reserve_alimentaire ) ; le reste en arrieres ( EU-SILC ilc_mdes06, ilc_mdes07 ) ; deux factures d electricite en
   arrieres et 20 jours : la coupure ( Code de fourniture d electricite ), rebranchee quand les arrieres sont soldes.
Genere par generer_patchs.py ( session HMT-126 ) ; a appliquer dans l ordre e, d. Chaque remplacement deja
fait est saute : idempotent.
   python patch_menages_e.py <racine>      ( racine/monde/pays/... )"""
import os, sys
racine = sys.argv[1]
FACULTATIFS = ('KEA', 'rmg_', '_revenu_declare_6_mois', '_poser_comptes_kea')   # le KEA : tronc seulement
REMPLACEMENTS = {
    'd03_economie': (
        (('\n\ndef budget_des_menages(p):\n    """Les parts du budget voulu, mesurees depuis l installation : ensemble et par quintile de revenu lisse."""\n',
          '\n\ndef reserve_alimentaire(p, jours=RESERVE_ALIMENTAIRE_J):\n    """( HMT-126 ) Ce que chaque menage garde pour manger avant de payer une facture, une cotisation ou une taxe :\n    `jours` jours de ration pour ses vivants presents, au prix affiche de son marche, TVA comprise ( drachmes, un tableau\n    par numero de menage ). Le reel grec : les menages pauvres ne sautent pas leurs repas pour payer, ils accumulent des\n    ARRIERES - en 2024, 32,0 % de la population a des arrieres de factures ( 65,6 % sous le seuil de pauvrete ) et 10,4 %\n    de loyer ou d emprunt ( 24,0 % ), les plus hauts de l Union ( 6,9 % et 3,1 % ) : Eurostat, EU-SILC ilc_mdes07 et\n    ilc_mdes06 ( ilc_mdes05, tous arrieres : 42,8 %, 77,9 % sous le seuil ). La privation de repas est bien plus rare.\n    Les suites des arrieres restent celles du reel : coupure d electricite ( domaine 11 ), expulsion ( domaine 13 ),\n    dettes a la caisse et au fisc ( domaines 4 et 6 )."""\n    w = p.w; d = p.domaine("economie"); n = len(w.menages)\n    v, _ = _tableaux_menages(p)\n    mi = _rang_marche_menages(w, d, n)\n    pn = np.array([w.marches[k].prix["nourriture"] for k in d.ids_marches])[mi] * (1.0 + w.gouv.tva)\n    ration = w.gouv.lois["rationnement_nourriture"] or C.NOURRITURE_PAR_JOUR\n    return float(jours) * ration * v * pn\n\n\ndef budget_des_menages(p):\n    """Les parts du budget voulu, mesurees depuis l installation : ensemble et par quintile de revenu lisse."""\n'), ),
    ),
    'd04_travail': (
        (('    mois n est credite qu a proportion de ce qui est paye."""\n    w = p.w; col = p.colonnes["habitant"]; st = col["tr_statut"]; tb = w.table; n = tb.n\n    # EN COLONNES ( 24/09 ) : les independants en activite trouves en vecteurs, payes dans l ordre des numeros\n    for i in np.nonzero((tb.vivant[:n] == 1) & (st[:n] == INDEPENDANT) & (tb.travail[:n] >= 0))[0].tolist():\n        m = COTISATION_INDEPENDANT_MOIS.get(_role_de(tb, i))\n        if m is None: continue\n        paye, du = _payer(p, _menage_de(tb, i), d.caisse, m, "cotisation_independant")\n        _cote(p, d, "cotisation_independant", paye)\n        f = paye / m\n',
          '    mois n est credite qu a proportion de ce qui est paye."""\n    w = p.w; col = p.colonnes["habitant"]; st = col["tr_statut"]; tb = w.table; n = tb.n\n    # HMT-126 : le menage paie sa cotisation sur ce qu il a au-dela de sa semaine de nourriture ( domaine 3,\n    # reserve_alimentaire ) ; le reste est une dette envers la caisse, comme les arrieres de cotisations des independants\n    # grecs aupres de l e-EFKA ( recouvres par le KEAO ; ordre de grandeur a verifier ).\n    res = ECO.reserve_alimentaire(p)\n    # EN COLONNES ( 24/09 ) : les independants en activite trouves en vecteurs, payes dans l ordre des numeros\n    for i in np.nonzero((tb.vivant[:n] == 1) & (st[:n] == INDEPENDANT) & (tb.travail[:n] >= 0))[0].tolist():\n        m = COTISATION_INDEPENDANT_MOIS.get(_role_de(tb, i))\n        if m is None: continue\n        mg = _menage_de(tb, i)\n        libre = max(0.0, mg.caisse - (float(res[mg.id]) if mg.id < len(res) else 0.0))\n        paye = p.socle.livre.transferer(mg, d.caisse, min(m, libre), "cotisation_independant")\n        du = m - paye\n        if du > TOL: p.socle.creances.constater(d.caisse, mg, du, "cotisation_independant", p.jour)\n        else: du = 0.0\n        _cote(p, d, "cotisation_independant", paye)\n        f = paye / m\n'), ),
    ),
    'd06_etat': (
        (('\n# ================================================================== API pour les autres domaines\ndef percevoir(p, payeur, montant, impot):\n    """Un impot ou une redevance d un autre domaine ( enfia, taxe_locale, droits_permis, droit_de_douane, tva_import ),\n    paye a l Etat ; ce que la caisse ne couvre pas devient une creance de l Etat. Rend ( paye, creance ou None )."""\n    if impot not in ("enfia", "taxe_locale", "droits_permis", "droit_de_douane", "tva_import"):\n        raise ValueError(f"impot inconnu {impot!r}")\n    if not 0.0 <= montant < math.inf: raise ValueError(f"montant invalide {montant!r}")\n    e = _etat(p); w = p.w\n    paye = p.socle.livre.transferer(payeur, w.gouv, montant, impot)\n    cr = None\n    if montant - paye > 1e-6:\n',
          '\n# ================================================================== API pour les autres domaines\ndef percevoir(p, payeur, montant, impot, plafond=None):\n    """Un impot ou une redevance d un autre domaine ( enfia, taxe_locale, droits_permis, droit_de_douane, tva_import ),\n    paye a l Etat ; ce que la caisse ne couvre pas devient une creance de l Etat. `plafond` : ce que le payeur peut y\n    mettre ( un menage garde sa semaine de nourriture, HMT-126 ) ; le reste devient aussi une creance. Rend ( paye,\n    creance ou None )."""\n    if impot not in ("enfia", "taxe_locale", "droits_permis", "droit_de_douane", "tva_import"):\n        raise ValueError(f"impot inconnu {impot!r}")\n    if not 0.0 <= montant < math.inf: raise ValueError(f"montant invalide {montant!r}")\n    e = _etat(p); w = p.w\n    paye = p.socle.livre.transferer(payeur, w.gouv, montant if plafond is None else min(montant, max(0.0, plafond)), impot)\n    cr = None\n    if montant - paye > 1e-6:\n'), ),
    ),
    'd11_energie': (
        (('   charges, meteo de l heure, journal horaire, cumuls ), Energie ( l etat du domaine ). Deux adaptateurs ( StocksE1,\n   ReseauE1 ) laissent le grand livre ecrire dans les dictionnaires du moteur. Colonnes par menage : en_du ( la facture\n   qui court, drachmes ), en_arrieres ( l impaye ). Unites : 1 unite de liquide = 10 litres ( le gazole du moteur :\n   0,03 unite par km = 30 l aux 100 km d un camion ), ~0,1 MWh PCI par unite de combustible, 1 unite d electricite = 10 kWh.\n2. Invariants. BIENS : tout passe par le grand livre, sous des motifs de biens nommes ( extraction, oleoduc, raffinage,\n',
          '   charges, meteo de l heure, journal horaire, cumuls ), Energie ( l etat du domaine ). Deux adaptateurs ( StocksE1,\n   ReseauE1 ) laissent le grand livre ecrire dans les dictionnaires du moteur. Colonnes par menage : en_du ( la facture\n   qui court, drachmes ), en_arrieres ( l impaye ), et ( HMT-126 ) en_impayees ( factures de suite laissees en arrieres ),\n   en_coupure_j ( jour ou l ordre de coupure s execute, -1 ), en_coupe ( compteur coupe pour impaye ). Unites : 1 unite de liquide = 10 litres ( le gazole du moteur :\n   0,03 unite par km = 30 l aux 100 km d un camion ), ~0,1 MWh PCI par unite de combustible, 1 unite d electricite = 10 kWh.\n2. Invariants. BIENS : tout passe par le grand livre, sous des motifs de biens nommes ( extraction, oleoduc, raffinage,\n'), ),
        (('VOLL_DR_KWH = 10.0                    # valeur de l energie non servie ( a calibrer : 5-20 euros le kWh, ACER )\nJOURS_FACTURE = 30                    # un menage recoit sa facture tous les 30 jours ( decale par menage )\nFONDS_ROULEMENT_J, PLAFOND_CAISSE_J, DOTATION_J = 7, 15, 7\n\n',
          'VOLL_DR_KWH = 10.0                    # valeur de l energie non servie ( a calibrer : 5-20 euros le kWh, ACER )\nJOURS_FACTURE = 30                    # un menage recoit sa facture tous les 30 jours ( decale par menage )\n# ( HMT-126 ) Le menage paie sa facture sur ce qu il a au-dela de sa semaine de nourriture ( domaine 3,\n# reserve_alimentaire ) : le reste reste en arrieres ( en_arrieres ). La suite reelle d un impaye : le Code de fourniture\n# d electricite ( Κώδικας Προμήθειας Ηλεκτρικής Ενέργειας ) - la facture impayee reparait sur la suivante comme echue,\n# le fournisseur propose sous 5 jours un arrangement, le client a 5 jours pour repondre, puis l ordre de coupure est\n# notifie et le compteur est coupe 10 jours plus tard s il n a pas regle ( resume newpost.gr, « Απλήρωτος λογαριασμός\n# ρεύματος : πότε έρχεται η διακοπή » ). Ici : deux factures de suite laissees en arrieres, et 20 jours apres la seconde,\n# la coupure ( le menage n est plus servi ni facture ; ses arrieres restent dus ) ; le reglement des arrieres, a une date\n# de facture, le rebranche. Les clients vulnerables ( KOT, protection d hiver et d ete ) ne sont pas distingues : a faire.\nFACTURES_AVANT_COUPURE = 2\nDELAI_COUPURE_J = 5 + 5 + 10\nCOLONNES_COUPURE = (("en_impayees", np.int8, 0), ("en_coupure_j", np.int32, -1), ("en_coupe", np.int8, 0))\nFONDS_ROULEMENT_J, PLAFOND_CAISSE_J, DOTATION_J = 7, 15, 7\n\n'), ),
        (('            ok = (z >= 0) & (viv > 0)\n            mz[ok] = z[ok]; mv[ok] = viv[ok]\n    hab = np.bincount(mz[mz >= 0], weights=mv[mz >= 0], minlength=nz)[:nz] if nz else np.zeros(0)\n    for k, c in enumerate(E.zones): c.hab = float(hab[k])\n',
          '            ok = (z >= 0) & (viv > 0)\n            mz[ok] = z[ok]; mv[ok] = viv[ok]\n    mv[_coupes(p, n)] = 0.0                     # HMT-126 : un compteur coupe ne tire rien ; sa zone reste pour ses arrieres\n    hab = np.bincount(mz[mz >= 0], weights=mv[mz >= 0], minlength=nz)[:nz] if nz else np.zeros(0)\n    for k, c in enumerate(E.zones): c.hab = float(hab[k])\n'), ),
        (('\n\ndef _factures_menages(p, E, tarif):\n    """Le residentiel servi de chaque zone est reparti sur ses menages par personne ; chaque menage paie sa facture tous\n    les 30 jours ( decale par menage ) ; ce qu il ne peut pas payer reste en arrieres."""\n    w = p.w\n    n = len(E.mg_zone)\n',
          '\n\ndef _coupes(p, n):\n    """( HMT-126 ) Les compteurs coupes pour impaye ( masque des n premiers menages ) ; applique d abord les ordres de\n    coupure arrives a echeance sur des arrieres toujours dus."""\n    cm = p.colonnes["menage"]\n    if "en_coupe" not in cm:                     # un monde installe avant ( instantane relu )\n        for c, dt, v in COLONNES_COUPURE: cm.ajouter(c, dt, v)\n        J = p.socle.journal\n        for t in ("coupure_impaye", "rebranchement"):\n            if t not in getattr(J, "types", {}): J.declarer(t, "energie", "compte")\n    cm.assurer(n)\n    cj, cp, arr = cm["en_coupure_j"][:n], cm["en_coupe"][:n], cm["en_arrieres"][:n]\n    ech = (cj >= 0) & (p.jour >= cj) & (cp == 0) & (arr > EPS)\n    if ech.any():\n        cp[ech] = 1\n        p.compter("coupure_impaye", float(ech.sum()))\n    return cp == 1\n\n\ndef _factures_menages(p, E, tarif):\n    """Le residentiel servi de chaque zone est reparti sur ses menages par personne ; chaque menage paie sa facture tous\n    les 30 jours ( decale par menage ), sur ce qu il a au-dela de sa semaine de nourriture ; le reste reste en\n    arrieres. Deux factures de suite en arrieres : l ordre de coupure, execute 20 jours plus tard s il n a pas regle ;\n    des arrieres soldes rebranchent le compteur ( HMT-126 )."""\n    w = p.w\n    n = len(E.mg_zone)\n'), ),
        (('    du[:n] += add\n    ids = np.arange(n)\n    for i in np.nonzero(ok & ((ids + p.jour) % JOURS_FACTURE == 0) & (du[:n] + arr[:n] > EPS))[0].tolist():\n        mg = w.menages[i]\n        G = E.par_ile[E.zones[int(zi[i])].ile].gestionnaire\n        voulu = float(du[i] + arr[i])\n        paye = p.socle.livre.transferer(mg, G, voulu, "facture_electricite")\n        E.factures += paye\n        du[i] = 0.0; arr[i] = voulu - paye\n        if voulu - paye > EPS: E.impayes += voulu - paye; p.compter("facture_impayee", voulu - paye)\n\n\n',
          '    du[:n] += add\n    ids = np.arange(n)\n    a_payer = np.nonzero(ok & ((ids + p.jour) % JOURS_FACTURE == 0) & (du[:n] + arr[:n] > EPS))[0]\n    if not len(a_payer): return\n    _coupes(p, n)\n    cm = p.colonnes["menage"]; imp, cj, cp = cm["en_impayees"], cm["en_coupure_j"], cm["en_coupe"]\n    res = ECO.reserve_alimentaire(p)\n    for i in a_payer.tolist():\n        mg = w.menages[i]\n        G = E.par_ile[E.zones[int(zi[i])].ile].gestionnaire\n        voulu = float(du[i] + arr[i])\n        libre = max(0.0, mg.caisse - (float(res[i]) if i < len(res) else 0.0))\n        paye = p.socle.livre.transferer(mg, G, min(voulu, libre), "facture_electricite")\n        E.factures += paye\n        du[i] = 0.0; arr[i] = voulu - paye\n        if voulu - paye > EPS:\n            E.impayes += voulu - paye; p.compter("facture_impayee", voulu - paye)\n            imp[i] = min(100, int(imp[i]) + 1)\n            if imp[i] >= FACTURES_AVANT_COUPURE and cj[i] < 0: cj[i] = p.jour + DELAI_COUPURE_J\n        else:\n            arr[i] = 0.0; imp[i] = 0; cj[i] = -1\n            if cp[i]: cp[i] = 0; p.compter("rebranchement")\n\n\n'), ),
        (('        J.declarer(t, "energie", "individuel", champs)\n    for t in ("energie_non_servie", "ecretement", "demarrage_groupe", "import_combustible", "export_petrolier",\n              "facture_impayee", "manque_combustible", "manque_eau_energie"):\n        J.declarer(t, "energie", "compte")\n    cm = p.colonnes["menage"]\n    cm.ajouter("en_du", np.float64, 0.0); cm.ajouter("en_arrieres", np.float64, 0.0)\n    cm.assurer(len(w.menages))\n    _declarer_modeles(p)\n',
          '        J.declarer(t, "energie", "individuel", champs)\n    for t in ("energie_non_servie", "ecretement", "demarrage_groupe", "import_combustible", "export_petrolier",\n              "facture_impayee", "manque_combustible", "manque_eau_energie", "coupure_impaye", "rebranchement"):\n        J.declarer(t, "energie", "compte")\n    cm = p.colonnes["menage"]\n    cm.ajouter("en_du", np.float64, 0.0); cm.ajouter("en_arrieres", np.float64, 0.0)\n    for c, dt, v in COLONNES_COUPURE:\n        if c not in cm: cm.ajouter(c, dt, v)\n    cm.assurer(len(w.menages))\n    _declarer_modeles(p)\n'), ),
    ),
    'd12_services_publics': (
        (('from .. import config as C\nfrom ..socle import decision as D\nfrom . import pays as P, d02_banques as BQ, d06_etat as ET, d08_territoire as TER\n\nEPS = 1e-9\n',
          'from .. import config as C\nfrom ..socle import decision as D\nfrom . import pays as P, d02_banques as BQ, d03_economie as ECO, d06_etat as ET, d08_territoire as TER\n\nEPS = 1e-9\n'), ),
        (('def _factures(p):\n    """Les factures d eau des menages ( vectorisees ) ; chaque menage paie tous les 30 jours, decale par menage, avec la\n    TVA de l eau ; puis la taxe locale ( proprete, eclairage ) a l Etat."""\n    S = _sp(p); w = p.w; L = p.socle.livre; E = S.eau\n    n = len(S.mg_lieu)\n',
          'def _factures(p):\n    """Les factures d eau des menages ( vectorisees ) ; chaque menage paie tous les 30 jours, decale par menage, avec la\n    TVA de l eau ; puis la taxe locale ( proprete, eclairage ) a l Etat. ( HMT-126 ) Le menage paie l une et l autre sur ce\n    qu il a au-dela de sa semaine de nourriture ( domaine 3, reserve_alimentaire ) : le reste reste en arrieres ( eau ) ou\n    devient une creance du fisc ( taxe locale ). Les regies grecques ( DEYA ) coupent l eau apres des impayes, selon leur\n    reglement : non modelise, a faire."""\n    S = _sp(p); w = p.w; L = p.socle.livre; E = S.eau\n    n = len(S.mg_lieu)\n'), ),
        (('    T = p.domaine("territoire")\n    ids = np.arange(n)\n    for i in np.nonzero(ok & ((ids + p.jour) % JOURS_FACTURE == 0) & (du[:n] + arr[:n] > EPS))[0].tolist():\n        mg = w.menages[i]\n        r = S.regies[S.regie_ile[T.iles[int(T.lieu_ile[k[i]])]]]\n        voulu = float(du[i] + arr[i])\n        paye = L.transferer(mg, r, voulu, "facture_eau")\n        part_eau = TARIF_EAU / float(tarif[i]) if tarif[i] > 0 else 1.0\n        if paye > 0: ET.percevoir_tva(p, mg, "eau_potable", paye * part_eau)\n        du[i] = 0.0; arr[i] = voulu - paye\n        if voulu - paye > EPS: p.compter("facture_eau_impayee", voulu - paye)\n    for i in np.nonzero(ok & ((ids + p.jour) % JOURS_TAXE == 7))[0].tolist():\n        ET.percevoir(p, w.menages[i], ET.taxe_locale(SURFACE_LOGEMENT_M2, JOURS_TAXE), "taxe_locale")\n\n\n',
          '    T = p.domaine("territoire")\n    ids = np.arange(n)\n    fact = np.nonzero(ok & ((ids + p.jour) % JOURS_FACTURE == 0) & (du[:n] + arr[:n] > EPS))[0]\n    taxe = np.nonzero(ok & ((ids + p.jour) % JOURS_TAXE == 7))[0]\n    res = ECO.reserve_alimentaire(p) if len(fact) or len(taxe) else None\n    for i in fact.tolist():\n        mg = w.menages[i]\n        r = S.regies[S.regie_ile[T.iles[int(T.lieu_ile[k[i]])]]]\n        voulu = float(du[i] + arr[i])\n        part_eau = TARIF_EAU / float(tarif[i]) if tarif[i] > 0 else 1.0\n        libre = max(0.0, mg.caisse - (float(res[i]) if i < len(res) else 0.0)) / (1.0 + ET.taux_tva(p, "eau_potable") * part_eau)\n        paye = L.transferer(mg, r, min(voulu, libre), "facture_eau")\n        if paye > 0: ET.percevoir_tva(p, mg, "eau_potable", paye * part_eau)\n        du[i] = 0.0; arr[i] = voulu - paye\n        if voulu - paye > EPS: p.compter("facture_eau_impayee", voulu - paye)\n    for i in taxe.tolist():\n        mg = w.menages[i]\n        ET.percevoir(p, mg, ET.taxe_locale(SURFACE_LOGEMENT_M2, JOURS_TAXE), "taxe_locale",\n                     plafond=mg.caisse - (float(res[i]) if i < len(res) else 0.0))\n\n\n'), ),
    ),
}


for f, blocs in REMPLACEMENTS.items():
    chemin = os.path.join(racine, "monde", "pays", f + ".py")
    s = open(chemin).read()
    faits = deja = 0
    for variantes in blocs:                      # la forme du tronc, puis celle de la reference d origine
        if any(neuf in s for _, neuf in variantes): deja += 1; continue
        v = next(((vieux, neuf) for vieux, neuf in variantes if s.count(vieux) == 1), None)
        if v is None:
            if any(m in variantes[0][0] or m in variantes[0][1] for m in FACULTATIFS): continue
            raise AssertionError((chemin, variantes[0][0][:160]))
        s = s.replace(v[0], v[1]); faits += 1
    open(chemin, "w").write(s); print("corrige :" if faits else "deja corrige :", chemin, faits, "remplacements", deja, "deja faits")
